{{- if .Values.autoscaling.enabled }}
{{- range $key, $service := .Values.backend }}
{{- if $service.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "smile-health.fullname" $ }}-{{ $key }}
  labels:
    {{- include "smile-health.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $key }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "smile-health.fullname" $ }}-{{ $key }}
  minReplicas: {{ $.Values.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $.Values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}

{{- range $key, $service := .Values.frontend }}
{{- if $service.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "smile-health.fullname" $ }}-{{ $key }}
  labels:
    {{- include "smile-health.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $key }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "smile-health.fullname" $ }}-{{ $key }}
  minReplicas: {{ $.Values.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $.Values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
{{- end }}
